# Netlify Configuration File
# Docs: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command
  command = "npm run build"
  
  # Directory with the build output
  publish = "dist"
  
  # Node version
  environment = { NODE_VERSION = "18" }

# Redirects and rewrites for Single Page Application (SPA)
# This ensures all routes work correctly (including /admin-signup-secret-2024)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables placeholder
# Set these in Netlify Dashboard: Site Settings > Build & Deploy > Environment Variables
# VITE_SUPABASE_URL
# VITE_SUPABASE_ANON_KEY
